# Generated by Django 5.2.1 on 2025-05-17 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0002_initial'),
        ('onboarding', '0001_initial'),
        ('peoples', '0001_initial'),
        ('tenants', '0001_initial'),
        ('y_helpdesk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.asset', verbose_name='Belongs to'),
        ),
        migrations.AddField(
            model_name='asset',
            name='servprov',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_serv_providers', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='asset',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_subcategories', to='onboarding.typeassist', verbose_name='Sub Category'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_types', to='onboarding.typeassist', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='asset',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_units', to='onboarding.typeassist', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='assetlog',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='activity.asset', verbose_name='Asset'),
        ),
        migrations.AddField(
            model_name='assetlog',
            name='bu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt', verbose_name='Bu'),
        ),
        migrations.AddField(
            model_name='assetlog',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assetlog_client', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='assetlog',
            name='people',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='People'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='bu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachment',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachment',
            name='ownername',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.typeassist'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='deviceeventlog',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt'),
        ),
        migrations.AddField(
            model_name='deviceeventlog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='deviveevents_clients', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='deviceeventlog',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deviceeventlog',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deviceeventlog',
            name='people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='deviceevent_people', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.asset', verbose_name='Asset'),
        ),
        migrations.AddField(
            model_name='job',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_bus', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='job',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_clients', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='job',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='geofence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.geofencemaster', verbose_name='Geofence'),
        ),
        migrations.AddField(
            model_name='job',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.job', verbose_name='Belongs to'),
        ),
        migrations.AddField(
            model_name='job',
            name='people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_aaatops', to=settings.AUTH_USER_MODEL, verbose_name='Aggresive auto-assign to People'),
        ),
        migrations.AddField(
            model_name='job',
            name='pgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_pgroup', to='peoples.pgroup', verbose_name='People Group'),
        ),
        migrations.AddField(
            model_name='job',
            name='sgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_sgroup', to='peoples.pgroup', verbose_name='Site Group'),
        ),
        migrations.AddField(
            model_name='job',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_shifts', to='onboarding.shift', verbose_name='Shift'),
        ),
        migrations.AddField(
            model_name='job',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='job',
            name='ticketcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_tktcategories', to='onboarding.typeassist', verbose_name='Notify Category'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneed_assets', to='activity.asset', verbose_name='Asset'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneedf_bus', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneed_clients', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobs', to='activity.job', verbose_name='Job'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.jobneed', verbose_name='Belongs to'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='People'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='performedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneed_performedby', to=settings.AUTH_USER_MODEL, verbose_name='Performed by'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='pgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneed_pgroup', to='peoples.pgroup', verbose_name='People Group'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='remarkstype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='remark_types', to='onboarding.typeassist'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='sgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneed_sgroup', to='peoples.pgroup', verbose_name='Site Group'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobneed_ticket', to='y_helpdesk.ticket', verbose_name='Ticket'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='ticketcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.typeassist', verbose_name='Notify Category'),
        ),
        migrations.AddField(
            model_name='jobneeddetails',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobneeddetails',
            name='jobneed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.jobneed', verbose_name='Jobneed'),
        ),
        migrations.AddField(
            model_name='jobneeddetails',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobneeddetails',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='location',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='location_bus', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='location',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='location_clients', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='location',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.location', verbose_name='Belongs to'),
        ),
        migrations.AddField(
            model_name='location',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='location_types', to='onboarding.typeassist', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='category_types', to='onboarding.typeassist', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='question',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='question',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='question',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='unit_types', to='onboarding.typeassist', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='jobneeddetails',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.question', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='qset_bus', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='qset_clients', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionset',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionset',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.questionset', verbose_name='Belongs To'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='jobneeddetails',
            name='qset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='questions_qset', to='activity.questionset', verbose_name='Question Set'),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='qset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.questionset', verbose_name='QuestionSet'),
        ),
        migrations.AddField(
            model_name='job',
            name='qset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.questionset', verbose_name='QuestionSet'),
        ),
        migrations.AddField(
            model_name='questionsetbelonging',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='qsetbelong_bu', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='questionsetbelonging',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='qsetbelong_client', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='questionsetbelonging',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionsetbelonging',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionsetbelonging',
            name='qset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.questionset', verbose_name='Question Set'),
        ),
        migrations.AddField(
            model_name='questionsetbelonging',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.question', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='questionsetbelonging',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('loccode', 'bu', 'client'), name='loccode_bu_client_uk'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('assetcode', 'bu', 'client'), name='assetcode_client_uk'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('quesname', 'answertype', 'client'), name='ques_name_type_client_uk'),
        ),
        migrations.AddConstraint(
            model_name='questionset',
            constraint=models.UniqueConstraint(fields=('qsetname', 'parent', 'type', 'client', 'bu'), name='name_type_parent_type_client_bu_uk'),
        ),
        migrations.AddConstraint(
            model_name='questionset',
            constraint=models.CheckConstraint(condition=models.Q(('seqno__gte', 0)), name='slno_gte_0_ck'),
        ),
        migrations.AddConstraint(
            model_name='jobneed',
            constraint=models.CheckConstraint(condition=models.Q(('gracetime__gte', 0)), name='jobneed_gracetime_gte_0_ck'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('jobname', 'asset', 'qset', 'parent', 'identifier', 'client'), name='jobname_asset_qset_id_parent_identifier_client_uk'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('gracetime__gte', 0)), name='gracetime_gte_0_ck'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('planduration__gte', 0)), name='planduration_gte_0_ck'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('expirytime__gte', 0)), name='expirytime_gte_0_ck'),
        ),
        migrations.AddConstraint(
            model_name='questionsetbelonging',
            constraint=models.UniqueConstraint(fields=('qset', 'question', 'client', 'bu'), name='qset_question_client_bu_uk'),
        ),
    ]
