# Generated by Django 5.2.1 on 2025-06-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsetbelonging',
            name='max',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Max'),
        ),
        migrations.AlterField(
            model_name='questionsetbelonging',
            name='min',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Min'),
        ),
    ]
