# Generated by Django 5.2.1 on 2025-06-20 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the request')),
                ('username', models.CharField(blank=True, help_text='Username attempted (if available)', max_length=150, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string', null=True)),
                ('attempt_time', models.DateTimeField(default=django.utils.timezone.now, help_text='When the attempt was made')),
                ('attempt_type', models.CharField(choices=[('login', 'Login Attempt'), ('password_reset', 'Password Reset'), ('api_access', 'API Access'), ('form_submission', 'Form Submission')], default='login', help_text='Type of attempt being rate limited', max_length=50)),
                ('success', models.BooleanField(default=False, help_text='Whether the attempt was successful')),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for failure (invalid password, blocked, etc.)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
            ],
            options={
                'db_table': 'auth_rate_limit_attempts',
                'ordering': ['-attempt_time'],
                'indexes': [models.Index(fields=['ip_address', 'attempt_time'], name='auth_rate_l_ip_addr_b7fc4a_idx'), models.Index(fields=['username', 'attempt_time'], name='auth_rate_l_usernam_88c490_idx'), models.Index(fields=['success', 'attempt_time'], name='auth_rate_l_success_cb275b_idx')],
            },
        ),
    ]
