# Generated by Django 5.2.1 on 2025-05-17 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onboarding', '0001_initial'),
        ('peoples', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bt',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bt',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bt',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='onboarding.bt', verbose_name='Belongs To'),
        ),
        migrations.AddField(
            model_name='bt',
            name='siteincharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='siteincharge', to=settings.AUTH_USER_MODEL, verbose_name='Site Incharge'),
        ),
        migrations.AddField(
            model_name='bt',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='device',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='device',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='lastloggedinuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Last Logged In User'),
        ),
        migrations.AddField(
            model_name='device',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='downtimehistory',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='downtimehistory',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='downtimehistory',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='geofencemaster',
            name='alerttogroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='peoples.pgroup', verbose_name='Alert to Group'),
        ),
        migrations.AddField(
            model_name='geofencemaster',
            name='alerttopeople',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AddField(
            model_name='geofencemaster',
            name='bu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='for_sites', to='onboarding.bt', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='geofencemaster',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='for_clients', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='geofencemaster',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='geofencemaster',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shift',
            name='bu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='shift_bu', to='onboarding.bt', verbose_name='Buisiness View'),
        ),
        migrations.AddField(
            model_name='shift',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='shift_client', to='onboarding.bt', verbose_name='Buisiness View'),
        ),
        migrations.AddField(
            model_name='shift',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shift',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shift',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='assignedhandset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.device', verbose_name='Assigned Handset'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='typeassist',
            name='bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ta_bus', to='onboarding.bt', verbose_name='Buisiness View'),
        ),
        migrations.AddField(
            model_name='typeassist',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ta_clients', to='onboarding.bt', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='typeassist',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_cusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typeassist',
            name='muser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typeassist',
            name='tatype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='onboarding.typeassist', verbose_name='TypeAssist'),
        ),
        migrations.AddField(
            model_name='typeassist',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='shift',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.typeassist', verbose_name='Buisiness View'),
        ),
        migrations.AddField(
            model_name='bt',
            name='butype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bu_butypes', to='onboarding.typeassist', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='bt',
            name='identifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bu_idfs', to='onboarding.typeassist', verbose_name='Identifier'),
        ),
        migrations.AddConstraint(
            model_name='geofencemaster',
            constraint=models.UniqueConstraint(fields=('gfcode', 'bu'), name='gfcode_bu_uk'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('startdate', 'enddate', 'client'), name='startdate_enddate_client_uk'),
        ),
        migrations.AddConstraint(
            model_name='typeassist',
            constraint=models.UniqueConstraint(fields=('tacode', 'tatype', 'client'), name='code_unique'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('shiftname', 'bu', 'designation', 'client'), name='shiftname_bu_desgn_client_uk'),
        ),
        migrations.AddConstraint(
            model_name='bt',
            constraint=models.UniqueConstraint(fields=('bucode', 'parent', 'identifier'), name='bu_bucode_parent_identifier_uk'),
        ),
    ]
