# Generated by Django 5.2.1 on 2025-05-17 07:54

import apps.peoples.models
import apps.y_helpdesk.managers
import apps.y_helpdesk.models
import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0002_initial'),
        ('onboarding', '0001_initial'),
        ('peoples', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='cdtz')),
                ('mdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='mdtz')),
                ('ctzoffset', models.IntegerField(default=-1, verbose_name='TimeZone')),
                ('body', models.CharField(max_length=500, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('MINUTE', 'MINUTE'), ('HOUR', 'HOUR'), ('DAY', 'DAY'), ('WEEK', 'WEEK')], default='DAY', max_length=10)),
                ('frequencyvalue', models.IntegerField(blank=True, null=True)),
                ('assignedfor', models.CharField(max_length=50)),
                ('notify', models.EmailField(blank=True, max_length=254, null=True)),
                ('assignedgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='escalation_grps', to='peoples.pgroup')),
                ('assignedperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='escalation_people', to=settings.AUTH_USER_MODEL)),
                ('bu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='esc_clients', to='onboarding.bt')),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_cusers', to=settings.AUTH_USER_MODEL)),
                ('escalationtemplate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='esc_types', to='onboarding.typeassist')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.job', verbose_name='Job')),
                ('muser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_musers', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'escalationmatrix',
                'ordering': ['mdtz'],
                'get_latest_by': ['mdtz', 'cdtz'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('frequencyvalue__gte', 0)), name='frequencyvalue_gte_0_ck'), models.CheckConstraint(condition=models.Q(('notify__isnull', True), ('notify', ''), ('notify__regex', '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$'), _connector='OR'), name='valid_notify_format')],
            },
            managers=[
                ('objects', apps.y_helpdesk.managers.ESCManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='cdtz')),
                ('mdtz', models.DateTimeField(default=apps.peoples.models.now, verbose_name='mdtz')),
                ('ctzoffset', models.IntegerField(default=-1, verbose_name='TimeZone')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, unique=True)),
                ('ticketno', models.CharField(max_length=200, null=True, unique=True)),
                ('ticketdesc', models.TextField()),
                ('comments', models.CharField(max_length=250, null=True)),
                ('identifier', models.CharField(choices=[('REQUEST', 'Request'), ('TICKET', 'Ticket')], default='TICKET', max_length=50, verbose_name='Identifier')),
                ('priority', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=50, null=True, verbose_name='Priority')),
                ('modifieddatetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, choices=[('NEW', 'New'), ('CANCELLED', 'Cancel'), ('RESOLVED', 'Resolved'), ('OPEN', 'Open'), ('ONHOLD', 'On Hold'), ('CLOSED', 'Closed')], default='NEW', max_length=50, null=True, verbose_name='Status')),
                ('ticketlog', models.JSONField(blank=True, default=apps.y_helpdesk.models.ticket_defaults, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('events', models.TextField(blank=True, null=True)),
                ('isescalated', models.BooleanField(default=False)),
                ('ticketsource', models.CharField(blank=True, choices=[('SYSTEMGENERATED', 'New Generated'), ('USERDEFINED', 'User Defined')], max_length=50, null=True)),
                ('attachmentcount', models.IntegerField(null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.asset')),
                ('assignedtogroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ticket_grps', to='peoples.pgroup')),
                ('assignedtopeople', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ticket_people', to=settings.AUTH_USER_MODEL)),
                ('bu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='onboarding.bt')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ticket_clients', to='onboarding.bt')),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_cusers', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.location')),
                ('muser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_musers', to=settings.AUTH_USER_MODEL)),
                ('performedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ticket_performedby', to=settings.AUTH_USER_MODEL)),
                ('qset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='activity.questionset')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('ticketcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ticketcategory_types', to='onboarding.typeassist')),
            ],
            options={
                'db_table': 'ticket',
                'ordering': ['mdtz'],
                'get_latest_by': ['cdtz', 'mdtz'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('bu', 'id', 'client'), name='bu_id_uk')],
            },
            managers=[
                ('objects', apps.y_helpdesk.managers.TicketManager()),
            ],
        ),
    ]
